# Generated by Django 5.1.4 on 2025-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_program_student_course_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
