# Generated by Django 5.1.4 on 2025-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_program_student_course_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Untitled Notification', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='submission_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
